version: "3"

services:
  socket:
    build: .
    command: yarn start
    container_name: client
    restart: unless-stopped
    volumes:
      - .:/client
      - /client/node_modules
    ports:
      - "3000:3000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge